CREATE TABLE IF NOT EXISTS tbl_transaction(
    id SERIAL PRIMARY KEY, 
    customer_id BIGINT NOT NULL REFERENCES tbl_customer(id),
    item_id BIGINT NOT NULL REFERENCES tbl_items(id),
    quantity INTEGER,
    price DECIMAL(10, 2) DEFAULT 0.00,
    created_at TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE  DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP DEFAULT NULL
);